#ifndef CONST_H
#define CONST_H

#define FONT_PATH "../Fonts/colour_brush/colour.ttf"

#define EXIT_BUTTON_X 765
#define EXIT_BUTTON_Y 760
#define FLUIDE_BUTTON_X 765
#define FLUIDE_BUTTON_Y 550
#define CHARGE_BUTTON_X 765
#define CHARGE_BUTTON_Y 655
#define TEXT_PARKING_SIMULATOR_X 450
#define TEXT_PARKING_SIMULATOR_Y 270

#define FIRST_LEFT_TOP_WALL_X 4
#define FIRST_LEFT_TOP_WALL_Y 100
#define FIRST_LEFT_BOTTOM_WALL_SHIFT_X 4
#define FIRST_LEFT_BOTTOM_WALL_SHIFT_Y 365
#define FIRST_LEFT_BOTTOM_WALL_X 4
#define FIRST_LEFT_BOTTOM_WALL_Y 845

#define NUMB_LEFT_TOP_WALL 22
#define NUMB_LEFT_TOP_WALL_SHIFT 2
#define NUMB_LEFT_BOTTOM_WALL_SHIFT 9 


#endif